// Generated by Tools/make_distractor_schedule.py — do not hand-edit.
// Regenerate with: python Tools/make_distractor_schedule.py
var DISTRACTOR_SCHEDULE = {
  "version": 1,
  "seed": 501,
  "duration_s": 210.0,
  "bursts": [
    {
      "id": 0,
      "t": 41.39,
      "duration_s": 0.6,
      "flash_hue": 200,
      "motion_dir": "rtl"
    },
    {
      "id": 1,
      "t": 67.79,
      "duration_s": 0.6,
      "flash_hue": 200,
      "motion_dir": "ttb"
    },
    {
      "id": 2,
      "t": 93.09,
      "duration_s": 0.6,
      "flash_hue": 45,
      "motion_dir": "ttb"
    },
    {
      "id": 3,
      "t": 116.61,
      "duration_s": 0.6,
      "flash_hue": 320,
      "motion_dir": "ltr"
    },
    {
      "id": 4,
      "t": 140.34,
      "duration_s": 0.6,
      "flash_hue": 0,
      "motion_dir": "ttb"
    },
    {
      "id": 5,
      "t": 162.48,
      "duration_s": 0.6,
      "flash_hue": 320,
      "motion_dir": "ltr"
    },
    {
      "id": 6,
      "t": 187.14,
      "duration_s": 0.6,
      "flash_hue": 45,
      "motion_dir": "btt"
    }
  ]
};
