// Block B probe presenter (Detection Response Task, ISO 17488 lineage).
// Loads a versioned JSON schedule (generated by Tools/make_probe_schedule.py) and shows a
// brief diamond flash at scripted times and az/el positions. The schedule clock pauses
// while head yaw is > m_deferYawDeg off forward, so every probe is displayable in-FOV
// (testing-strategy-v2 §4.2). Presses are matched to probes in the ISO window 100–2500 ms;
// everything else is a false alarm.
//
// Assign the two schedule TextAssets (copies of Assets/StreamingAssets/StudySchedules/
// probes_B1.json and probes_B2.json, or any JSON in the same format) and a probe material
// template. The template is required: Shader.Find is unreliable for stripped shaders on
// Android. Reuse SelectionDotMat.

using System;
using UnityEngine;

namespace PassthroughCameraSamples.ShaderSample.Study
{
    [Serializable]
    public class ProbeDef
    {
        public int id;
        public float t;          // seconds from condition start (schedule clock)
        public float az_deg;
        public float el_deg;
        public string band;      // "central" | "peripheral"
        public int duration_ms;
    }

    [Serializable]
    public class ProbeScheduleData
    {
        public int version;
        public string condition;
        public int seed;
        public ProbeDef[] probes;
    }

    public class ProbeScheduler : MonoBehaviour
    {
        [SerializeField] private TextAsset m_scheduleB1;
        [SerializeField] private TextAsset m_scheduleB2;

        [Tooltip("Unlit material template for the probe quad (serialized template — Shader.Find is stripped on Android builds).")]
        [SerializeField] private Material m_probeMaterialTemplate;
        [SerializeField] private Color m_probeColor = new(1f, 0.92f, 0.25f, 1f);
        [SerializeField] private float m_probeDistance = 8.5f;
        [Tooltip("Probe visual angle in degrees (pilot gate G3 calibrates this).")]
        [SerializeField, Range(0.5f, 6f)] private float m_probeSizeDeg = 2.0f;
        [Tooltip("Schedule clock pauses while head yaw is more than this off forward.")]
        [SerializeField, Range(5f, 60f)] private float m_deferYawDeg = 20f;

        public bool Running { get; private set; }
        public int ProbesFired { get; private set; }
        public int ProbesTotal => m_schedule?.probes?.Length ?? 0;
        public bool ScheduleExhausted => m_schedule != null && m_next >= m_schedule.probes.Length && m_activeId < 0;

        // ISO 17488 response window.
        private const float k_respMinS = 0.1f;
        private const float k_respMaxS = 2.5f;

        private ProbeScheduleData m_schedule;
        private int   m_next;
        private float m_clock;
        private float m_deferAccum;

        private GameObject m_probeGO;
        private Material   m_probeMat;

        private int   m_activeId = -1;
        private float m_onsetTime;
        private float m_hideAt;
        private float m_windowCloseAt;
        private bool  m_responded;

        public bool Begin(string condition)
        {
            var asset = condition == "B1" ? m_scheduleB1 : m_scheduleB2;
            if (asset == null)
            {
                Debug.LogError($"[ProbeScheduler] No schedule TextAsset assigned for {condition}.");
                return false;
            }
            var data = JsonUtility.FromJson<ProbeScheduleData>(asset.text);
            if (data?.probes == null || data.probes.Length == 0)
            {
                Debug.LogError($"[ProbeScheduler] Schedule for {condition} parsed empty.");
                return false;
            }
            return Begin(data);
        }

        /// <summary>Run an in-memory schedule (used for the practice probes).</summary>
        public bool Begin(ProbeScheduleData data)
        {
            if (data?.probes == null || data.probes.Length == 0) return false;
            m_schedule = data;
            m_next = 0; m_clock = 0f; m_deferAccum = 0f;
            m_activeId = -1; ProbesFired = 0; Running = true;
            EnsureProbeObject();
            StudyLogger.Instance?.LogEvent("PROBE_SCHEDULE",
                $"condition={data.condition};count={data.probes.Length};version={data.version};seed={data.seed}");
            return true;
        }

        public void StopRun()
        {
            Running = false;
            m_activeId = -1;
            if (m_probeGO != null) m_probeGO.SetActive(false);
        }

        private void Update()
        {
            if (!Running) return;
            var log  = StudyLogger.Instance;
            var head = Camera.main != null ? Camera.main.transform : transform;

            bool pressed = OVRInput.GetDown(OVRInput.RawButton.RIndexTrigger);
            if (pressed) log?.LogEvent("PRESS");

            // Resolve the active probe's response window.
            if (m_activeId >= 0)
            {
                if (m_probeGO.activeSelf && Time.time >= m_hideAt)
                    m_probeGO.SetActive(false);

                float since = Time.time - m_onsetTime;
                if (pressed && !m_responded)
                {
                    if (since >= k_respMinS && since <= k_respMaxS)
                    {
                        m_responded = true;
                        log?.LogEvent("PROBE_RESULT",
                            $"id={m_activeId};outcome=hit;rt_ms={(int)(since * 1000f)}");
                    }
                    else
                    {
                        // < 100 ms after onset: anticipation, counts as a false alarm.
                        log?.LogEvent("FALSE_ALARM", $"anticipation_near={m_activeId}");
                    }
                    pressed = false;
                }
                if (Time.time >= m_windowCloseAt)
                {
                    if (!m_responded)
                        log?.LogEvent("PROBE_RESULT", $"id={m_activeId};outcome=miss");
                    m_activeId = -1;
                }
            }

            if (pressed && m_activeId < 0)
                log?.LogEvent("FALSE_ALARM", "no_active_probe=1");

            // Schedule clock: advances only while the head is near forward.
            float headAzDeg = Mathf.Atan2(head.forward.x, head.forward.z) * Mathf.Rad2Deg;
            bool deferred = Mathf.Abs(Mathf.DeltaAngle(headAzDeg, 0f)) > m_deferYawDeg;
            bool nextDue  = m_next < m_schedule.probes.Length && m_clock >= m_schedule.probes[m_next].t;

            if (!deferred) m_clock += Time.deltaTime;
            else if (nextDue) m_deferAccum += Time.deltaTime;

            // Fire the next probe (one at a time; schedule spacing >> response window).
            if (m_activeId < 0 && !deferred && nextDue)
            {
                var p = m_schedule.probes[m_next];
                if (m_deferAccum > 0.05f)
                {
                    StudyLogger.Instance?.LogEvent("PROBE_DEFERRED",
                        $"id={p.id};delay_s={m_deferAccum.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)}");
                    m_deferAccum = 0f;
                }
                Fire(p, head);
                m_next++;
            }
        }

        private void Fire(ProbeDef p, Transform head)
        {
            float az = p.az_deg * Mathf.Deg2Rad;
            float el = p.el_deg * Mathf.Deg2Rad;
            float cosEl = Mathf.Cos(el);
            var dir = new Vector3(Mathf.Sin(az) * cosEl, Mathf.Sin(el), Mathf.Cos(az) * cosEl);

            float size = 2f * m_probeDistance * Mathf.Tan(0.5f * m_probeSizeDeg * Mathf.Deg2Rad);
            m_probeGO.transform.position   = head.position + dir * m_probeDistance;
            // 45° roll turns the cube's square silhouette into a diamond.
            m_probeGO.transform.rotation   = Quaternion.LookRotation(dir) * Quaternion.Euler(0f, 0f, 45f);
            m_probeGO.transform.localScale = new Vector3(size, size, size * 0.15f);
            m_probeGO.SetActive(true);

            m_activeId      = p.id;
            m_onsetTime     = Time.time;
            m_hideAt        = Time.time + p.duration_ms / 1000f;
            m_windowCloseAt = Time.time + k_respMaxS;
            m_responded     = false;
            ProbesFired++;

            StudyLogger.Instance?.LogEvent("PROBE_ONSET",
                $"id={p.id};band={p.band};az_deg={p.az_deg};el_deg={p.el_deg};duration_ms={p.duration_ms}");
        }

        private void EnsureProbeObject()
        {
            if (m_probeGO != null) return;
            // A thin cube, not a quad: a quad is single-sided and can be culled depending on
            // the mesh's facing convention. Same reason the selection dots are spheres.
            m_probeGO = GameObject.CreatePrimitive(PrimitiveType.Cube);
            m_probeGO.name = "StudyProbe";
            Destroy(m_probeGO.GetComponent<Collider>());
            m_probeMat = m_probeMaterialTemplate != null
                ? new Material(m_probeMaterialTemplate)
                : new Material(Shader.Find("Standard")); // editor fallback only — assign the template for device builds
            if (m_probeMaterialTemplate == null)
                Debug.LogWarning("[ProbeScheduler] No probe material template assigned — Shader.Find fallback will break in Android builds.");
            m_probeMat.color = m_probeColor;
            m_probeMat.renderQueue = 4300; // above vignette sphere (3000), dots (4000), toast (4100)
            m_probeGO.GetComponent<MeshRenderer>().sharedMaterial = m_probeMat;
            m_probeGO.SetActive(false);
        }

        private void OnDestroy()
        {
            if (m_probeGO != null) Destroy(m_probeGO);
            if (m_probeMat != null) Destroy(m_probeMat);
        }
    }
}
