#!/usr/bin/env python3
"""
Distractor-reel burst schedule generator for user-study Block A (workstation focus).

Emits the deterministic schedule TabletApp/distractor-reel.html plays back, per
Dissertation/testing-strategy-v2.md section 4.1:

  * Tablets show a "fast-cut, high-motion, bright" reel with scheduled salient
    event bursts (hard cuts to full-screen colour flashes + sudden motion) at
    fixed timestamps, ~every 20-30 s, identical across participants.
  * Reel duration matches a Block A condition (~3.5 min / 210 s).
  * Fully seeded: the same seed always yields the same schedule (repo-wide
    convention — see Tools/make_probe_schedule.py).

The continuous fast-cut/high-motion background in the HTML player is a pure
function of elapsed time (no RNG at runtime), so only the rarer, spec-mandated
bursts need a checked-in schedule file — that's what this script produces.

Usage (from the repo root):
    python Tools/make_distractor_schedule.py                 # canonical (seed 501)
    python Tools/make_distractor_schedule.py --seed 777 --duration 210

Output (default):
    Assets/StreamingAssets/StudySchedules/distractor_reel.json   (record copy)
    TabletApp/distractor_schedule.js                             (browser-loadable)
"""

import argparse
import json
import random
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_JSON_OUT = REPO_ROOT / "Assets/StreamingAssets/StudySchedules/distractor_reel.json"
DEFAULT_JS_OUT = REPO_ROOT / "TabletApp/distractor_schedule.js"

CANONICAL_SEED = 501
DURATION_S = 210.0          # matches a Block A condition (~3.5 min)
SETTLE_S = 15.0             # no burst before this (let the ambient reel establish first)
GAP_RANGE = (20.0, 30.0)    # s, uniform inter-burst jitter
BURST_DURATION_S = 0.6
FLASH_HUES = [0, 45, 200, 320]      # red, amber, blue, magenta — bright, saturated
MOTION_DIRS = ["ltr", "rtl", "ttb", "btt"]  # left-to-right, right-to-left, top-to-bottom, bottom-to-top


def build_schedule(seed: int, duration: float) -> dict:
    rng = random.Random(seed)
    bursts = []
    t = SETTLE_S + rng.uniform(*GAP_RANGE)
    i = 0
    while t <= duration - BURST_DURATION_S:
        bursts.append({
            "id": i,
            "t": round(t, 2),
            "duration_s": BURST_DURATION_S,
            "flash_hue": rng.choice(FLASH_HUES),
            "motion_dir": rng.choice(MOTION_DIRS),
        })
        t += rng.uniform(*GAP_RANGE)
        i += 1
    return {"version": 1, "seed": seed, "duration_s": duration, "bursts": bursts}


def sanity_check(schedule: dict) -> None:
    bursts = schedule["bursts"]
    assert len(bursts) >= 5, "too few bursts for a 3.5 min reel"
    assert bursts[0]["t"] >= SETTLE_S
    assert bursts[-1]["t"] <= schedule["duration_s"] - BURST_DURATION_S
    gaps = [bursts[0]["t"] - SETTLE_S] + [b["t"] - a["t"] for a, b in zip(bursts, bursts[1:])]
    assert all(GAP_RANGE[0] - 0.01 <= g <= GAP_RANGE[1] + 0.01 for g in gaps), gaps


def write_outputs(schedule: dict, json_out: Path, js_out: Path) -> None:
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(schedule, indent=2) + "\n", encoding="utf-8")

    js_out.parent.mkdir(parents=True, exist_ok=True)
    js_out.write_text(
        "// Generated by Tools/make_distractor_schedule.py — do not hand-edit.\n"
        "// Regenerate with: python Tools/make_distractor_schedule.py\n"
        # `var` (not `const`/`let`) so this becomes a `window` property — the
        # player checks `window.DISTRACTOR_SCHEDULE` to detect a load failure.
        f"var DISTRACTOR_SCHEDULE = {json.dumps(schedule, indent=2)};\n",
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", type=int, default=CANONICAL_SEED)
    ap.add_argument("--duration", type=float, default=DURATION_S)
    ap.add_argument("--json-out", type=Path, default=DEFAULT_JSON_OUT)
    ap.add_argument("--js-out", type=Path, default=DEFAULT_JS_OUT)
    args = ap.parse_args()

    schedule = build_schedule(args.seed, args.duration)
    sanity_check(schedule)
    write_outputs(schedule, args.json_out, args.js_out)

    print(f"wrote {args.json_out}")
    print(f"wrote {args.js_out}")
    print(f"{len(schedule['bursts'])} bursts over {args.duration:.0f}s "
          f"(seed {args.seed}, first at {schedule['bursts'][0]['t']:.1f}s, "
          f"last at {schedule['bursts'][-1]['t']:.1f}s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
